#:include app/kv/widgets/datepicker.kv
#:include app/kv/widgets/notification.kv

#:include app/kv/screens/add_card.kv
#:include app/kv/screens/add_category.kv
#:include app/kv/screens/add_expense.kv
#:include app/kv/screens/analysis.kv
#:include app/kv/screens/edit_card.kv
#:include app/kv/screens/edit_category.kv
#:include app/kv/screens/edit_expense.kv
#:include app/kv/screens/manage_data.kv
#:include app/kv/screens/menu.kv
