<ExpenseRow@BoxLayout>:
    orientation: "horizontal"
    size_hint_y: None
    height: dp(40)
    spacing: dp(5)

    Label:
        text: root.cartao
        size_hint_x: 0.1
    Label:
        text: root.nome
        size_hint_x: 0.3
    Label:
        text: root.valor
        size_hint_x: 0.2
    Label:
        text: root.tipo
        size_hint_x: 0.1
    Label:
        text: root.categoria
        size_hint_x: 0.2
    Label:
        text: root.data_recorrencia
        size_hint_x: 0.1
